---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: 'nfs-client'
  resources:
    requests:
      storage: 5Gi
